Admin Order Details
awesome-academy/naitei5_dn_supper-freen-mart pull request #12
Opened 2022-03-18 03:20 UTC by lcko1012

## Related Tickets
- [#46930](https://edu-redmine.sun-asterisk.vn/issues/46930)

## WHAT (optional)
- Create Oder Details page for admin
- Admin update Order's status

## HOW
- I create `show.html.erb` file to display order details. In this file, use `eager_load` to load all `order_items` of `order`
- Order's status updating by admin: I check correct status_id, order exist, if all is right, update status

## Evidence (Screenshot or Video)
![image](https://user-images.githubusercontent.com/65387111/158929913-9b2db3eb-3e53-40dc-ae02-c378c2fe1a73.png)

![image](https://user-images.githubusercontent.com/65387111/158931137-06ff98ef-a19f-42f4-b7d0-36738d034d38.png)

![image](https://user-images.githubusercontent.com/65387111/158931190-84c4a5f3-a0c2-4414-8eea-0342654326bf.png)

2022-03-18 03:31 UTC, trinhdvt requested changes
cmt

2022-03-18 03:31 UTC, trinhdvt commented on app/controllers/admin/orders_controller.rb
> +
```suggestion
```

2022-03-18 03:31 UTC, trinhdvt commented on app/controllers/admin/orders_controller.rb
> +  end
đưa code logic vào model

2022-03-18 10:23 UTC, trinhdvt requested changes
cmt

2022-03-18 10:23 UTC, trinhdvt commented on app/models/order.rb
> +  end
```suggestion
  def update_quantity &operator
    check_qtt = true
    products_record = order_items.map do |record|
      new_record = {
        id: record.product_id,
        quantity: operator.call(record.product.quantity, record.quantity)
      }
      return new_record if new_record[:quantity] >= 0

      check_qtt = false
      break
    end

    products.upsert_all products_record if check_qtt
    check_qtt
  end
```

2022-03-18 10:23 UTC, trinhdvt commented on app/models/order.rb
> +  end
```suggestion
  def status_to_int *status
    Order.statuses.values_at(*status).compact
  end

  def pending_to_deliver_receive stt_id
    require_stt = status_to_int(:pending, :delivering)
    status_pending? && require_stt.include?(stt_id)
  end
```

2022-03-18 10:23 UTC, trinhdvt commented on app/models/order.rb
> +      return update status: stt_id if update_quantity
```suggestion
      return update status: stt_id if update_quantity(&:-)
```

2022-03-18 10:23 UTC, trinhdvt commented on app/models/order.rb
> +      return update status: stt_id if update_quantity true
```suggestion
      return update status: stt_id if update_quantity(&:+)
```

2022-03-18 10:42 UTC, trinhdvt approved these changes
ok

2022-03-18 10:43 UTC, lcko1012 commented
ready

2022-03-18 15:03 UTC, anlvq-1058 reviewed
cmt

2022-03-18 15:03 UTC, ghost commented on app/controllers/admin/orders_controller.rb
> +    status_id = params[:status_id].to_i
em gửi tên trạng thái lên nhé

2022-03-18 15:03 UTC, ghost commented on app/controllers/admin/orders_controller.rb
> +    updated = @order.update_status status_id if @order.present?
```suggestion
    updated = @order.send("#{params[:status]}!") if @order.present?
```

2022-03-18 15:03 UTC, anlvq-1058 commented on app/models/order.rb
> +      status_pending? && stt_id == Order.statuses[:rejected]
```suggestion
     stt_id == Order.statuses[:received] && (status_delivering? || status_pending?)
```
như này đc ko em

2022-03-20 02:13 UTC, lcko1012 commented on app/models/order.rb
> +      status_pending? && stt_id == Order.statuses[:rejected]
dạ ở đây so sánh bằng với cả `rejected` và `received` ạ. Nên như vậy có lẽ không được ạ

2022-03-20 07:41 UTC, lcko1012 commented on app/controllers/admin/orders_controller.rb
> +    status_id = params[:status_id].to_i
Em đã thêm một thẻ `hidden_field_tag` để có thể gửi `status` lên ạ

2022-03-20 07:43 UTC, lcko1012 commented on app/controllers/admin/orders_controller.rb
> +    updated = @order.update_status status_id if @order.present?
dạ ở đây em đang gọi hàm `update_status` ạ, em không hiểu phần chỉnh sửa này lắm ạ :(

2022-03-20 12:55 UTC, trinhdvt requested changes
cmt

2022-03-20 12:55 UTC, trinhdvt commented on app/helpers/admin/orders_helper.rb
> +
```suggestion
    def status_with_key
      Order.statuses.map do |status, _|
        [t("statuses.#{status}"), status]
      end
    end
```

2022-03-20 12:55 UTC, trinhdvt commented on app/views/admin/orders/index.html.erb
>            selected: params[:option]),
cái `params[:option]` này là gì z nhỉ, nó từ đâu ra z 😞

2022-03-20 12:55 UTC, trinhdvt commented on app/controllers/admin/orders_controller.rb
> +    @orders = Order.status_search(params[:status]).newest
cái `params[:status]` gửi lên nó là dạng text mà nhỉ, mà cái hàm `status_search` truyền vào phải kiểu `int` mà nhỉ

2022-03-20 12:55 UTC, trinhdvt commented on app/views/admin/orders/show.html.erb
> +        <%= hidden_field_tag :status, :canceled, id: "status_param" %>
```suggestion
```

2022-03-20 12:55 UTC, trinhdvt commented on app/views/admin/orders/show.html.erb
> +            id: "status_id" %>
```suggestion
        <%= select_tag :status,
            options_for_select(status_with_key,
            selected: params[:option]),
            class: "status-select",
            id: "status_id" %>
```

2022-03-20 12:55 UTC, trinhdvt commented on app/views/admin/orders/show.html.erb
> +<%= javascript_pack_tag "order" %>
```suggestion
```

2022-03-20 12:55 UTC, trinhdvt commented on app/models/order.rb
>      def status_attributes_for_select
đưa hàm này vào helper ik

2022-03-20 12:55 UTC, trinhdvt commented on app/helpers/admin/orders_helper.rb
> +
hàm này sinh ra cái mảng [["Đã huỷ", "canceled"], ...], truyền cái này vào select_tag luôn để khỏi cần dùng js bắt sự kiện

2022-03-20 13:13 UTC, lcko1012 commented on app/controllers/admin/orders_controller.rb
> +    @orders = Order.status_search(params[:status]).newest
search status bằng string vẫn được mà nhỉ :(

2022-03-20 13:16 UTC, lcko1012 commented on app/helpers/admin/orders_helper.rb
> +
hàm như này có trong file order.rb rồi bà. thế tui bỏ nó vào helper

2022-03-20 13:28 UTC, lcko1012 commented on app/models/order.rb
>      def status_attributes_for_select
ok

2022-03-20 13:28 UTC, lcko1012 commented on app/controllers/admin/orders_controller.rb
> +    @orders = Order.status_search(params[:status]).newest
nó search bằng string được á

2022-03-20 13:28 UTC, lcko1012 commented on app/helpers/admin/orders_helper.rb
> +
ok zị tui nhét nó zô đây

2022-03-20 13:31 UTC, lcko1012 commented on app/views/admin/orders/show.html.erb
> +            id: "status_id" %>
updated

2022-03-20 13:44 UTC, trinhdvt approved these changes
ok

2022-03-20 14:39 UTC, vanvtt-0952 commented on app/controllers/admin/orders_controller.rb
> +    updated = @order.update_status new_stt if @order.present?
`if @order.present?` cần ko em
chị thấy chỗ này là order đã khác nil rồi chứ

2022-03-20 14:39 UTC, vanvtt-0952 commented on app/controllers/admin/orders_controller.rb
> +    @order = Order.with_items(params[:id])
Chị nghĩ ko cần viết scope chỗ này. như bên dưới tường minh hơn nhìu
```suggestion
    @order = Order.includes(:order_items).find_by(id: params[:id])
```

2022-03-20 14:39 UTC, vanvtt-0952 commented on app/controllers/admin/orders_controller.rb
> +  end
2 method này nên đặt ở helper rồi mixin hoặc đặt ở application controller, vì có tính tái sử dụng rất cao nhé

2022-03-20 14:39 UTC, vanvtt-0952 commented on app/controllers/admin/orders_controller.rb
> +    updated = @order.update_status new_stt if @order.present?
Ngoài ra, chị chưa thấy em dùng transaction nhỉ, chị thấy có 2 thao tác và update quantity và change status order

2022-03-21 03:43 UTC, lcko1012 commented on app/controllers/admin/orders_controller.rb
> +    updated = @order.update_status new_stt if @order.present?
update quantity với change status em có thực hiện ở hàm `update_status` trong file` order.rb` ạ

2022-03-21 08:06 UTC, lcko1012 commented on app/controllers/admin/orders_controller.rb
> +    updated = @order.update_status new_stt if @order.present?
dạ em update lại transaction trong file `order.rb` rồi ạ

2022-03-21 09:47 UTC, vanvtt-0952 commented on app/models/order.rb
> +      order.save!
```suggestion
      order.rejected!
```

2022-03-21 09:47 UTC, vanvtt-0952 commented on app/models/order.rb
> +      order.save!
```suggestion
      order.status = new_stt
      order.send("#{new_stt}!")
```

2022-03-21 09:47 UTC, merged