Admin orders list
awesome-academy/naitei5_dn_supper-freen-mart pull request #9
Opened 2022-03-16 08:08 UTC by lcko1012

## Related Tickets
- [#46928](https://edu-redmine.sun-asterisk.vn/issues/46928)

## WHAT (optional)
- Create orders list page for admin
- On orders admin page, can search by status

## HOW
- Use namespace for admin routes, check user is admin in `admin_controller.rb` file
- On orders admin page, use `gem ransack` for status searching feature
- Besides that, `I18n` is used for the `status` attribute

## Evidence (Screenshot or Video)
![image](https://user-images.githubusercontent.com/65387111/158544565-6cb0c88a-2f7b-4cc0-8f45-bf4aeee56490.png)
![image](https://user-images.githubusercontent.com/65387111/158544630-8d9647d1-b9d5-42e6-beae-c72cd3abb932.png)

2022-03-16 08:14 UTC, trinhdvt requested changes
cmt

2022-03-16 08:14 UTC, trinhdvt commented on app/controllers/admin/orders_controller.rb
> +    @q = Order.ransack(params[:q])
```suggestion
    @q = Order.ransack params[:q]
```

2022-03-16 08:14 UTC, trinhdvt commented on app/models/order.rb
> +  end
```suggestion
  class << self
    def status_attributes_for_select
      statuses.map do |status, id|
      [I18n.t("statuses.#{status}"), id]
    end
  end
```

2022-03-16 08:14 UTC, trinhdvt commented on app/views/admin/orders/_order.html.erb
> +    <td><%= number_to_currency(order.total) %></td>
```suggestion
    <td><%= number_to_currency order.total %></td>
```

2022-03-16 08:14 UTC, trinhdvt commented on config/routes.rb
> +      resources :orders, only: [:index]
```suggestion
      resources :orders, only: :index
```

2022-03-16 08:15 UTC, lcko1012 commented on app/controllers/admin/orders_controller.rb
> +    @q = Order.ransack(params[:q])
fix

2022-03-16 08:19 UTC, trinhdvt approved these changes
ok

2022-03-16 08:20 UTC, lcko1012 commented
ready

2022-03-16 10:51 UTC, trinhdvt approved these changes
ok

2022-03-17 00:55 UTC, anlvq-1058 reviewed
cmt

2022-03-17 00:55 UTC, anlvq-1058 commented on app/views/admin/orders/index.html.erb
> +    <%= form_tag admin_orders_path, class: "search-form", :method => 'get' do %>
```suggestion
    <%= form_tag admin_orders_path, class: "search-form", method: :get do %>
```

2022-03-17 00:55 UTC, anlvq-1058 commented on app/views/admin/orders/index.html.erb
> +          :selected =>params[:option]),
```suggestion
          selected: params[:option]),
```

2022-03-17 00:55 UTC, anlvq-1058 commented on app/models/order.rb
> +  scope :status_search, ->(status_id){where("status = ?", status_id)}
```suggestion
  scope :status_search, ->(status_id){where("status = ?", status_id) if status_id.present?}
```

2022-03-17 00:55 UTC, anlvq-1058 commented on app/controllers/admin/orders_controller.rb
> +              end
```suggestion
    @orders = Order.status_search(status_id).newest
```

2022-03-17 02:55 UTC, anlvq-1058 reviewed
cmt

2022-03-17 02:55 UTC, anlvq-1058 commented on app/controllers/admin/admin_controller.rb
> +  layout "admin"
```suggestion
  layout :admin
```
Để như này dc ko e

2022-03-17 03:20 UTC, anlvq-1058 reviewed
merged

2022-03-17 03:20 UTC, merged